# theme: jekyll-theme-slate
# show_downloads: true



# -----
# https://github.com/pages-themes/architect

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
- jemoji
show_downloads: true
title: Shaderfuses
description: Some Shadertoys for use with DaFusion
