

# See for example https://github.com/jobindjohn/obsidian-publish-mkdocs on how to
# publish Obsidian notes via MkDocs. See https://www.codeinsideout.com/blog/site-setup/create-site-project/#extend-the-theme
# for further information on customizations.

site_name: Shaderfuse
repo_url: https://github.com/nmbr73/Shaderfuse/
repo_name: Shaderfuse


nav:
   - Home: DESCRIPTION.md
   - Shaders List: README.md
   - Thumbnails: OVERVIEW.md
   - ...




theme:
  name: 'material'
  # name: bootstrap386

  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      # scheme: wsl
      scheme: slate
      primary: purple
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode



# Extensions
markdown_extensions:

  - nl2br # needed by 'callouts' cause newlines to be treated as hard breaks; like StackOverflow and GitHub flavored Markdown do
  - admonition # aka callouts; needed by 'callouts'
  - pymdownx.details # needed by 'callouts'; html5 <details><summary> for collapsible element

  - def_list # syntax: https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - attr_list # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde # subscript via ~
  - pymdownx.caret  # superscript via ^
  - pymdownx.mark # to mark text using ==some text==
  - pymdownx.smartsymbols # to render -->, <--, =/=, (c), 1st, 1/4, etc.
  - pymdownx.highlight:
  - pymdownx.saneheaders # to force header to have a space after the '#''
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true


plugins:
  - search
  - callouts
  - awesome-pages:
      collapse_single_pages: true
  # - tags:
  #     tags_file: Type.md


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nmbr73/Shaderfuse
      name: Shaderfuse on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Zb48E4z3Pg
      name: Fusion Developers Discord
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/playlist?list=PLqbIsaWc6bt1AuwEHF116QcFsNPKnLYHD
      name: Videos using Shaderfuses
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nmbr73
      name: nmbr73 on Twitter


