name: Create Atom for use with Reactor
on:
  push:
    branches:
      - main
    paths:
      - 'Shaders/**.fuse'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Update Atom Artifacts
      CI_COMMIT_AUTHOR: nmbr73 (CI)
      CI_COMMIT_EMAIL: 37710085+nmbr73@users.noreply.github.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
      - name: Run script to generate Atom
        run: cd 'Tools/Shell/' ; lua generate_atom.lua
      - name: Commit build artifacts
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git add Atom
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push


