name: Create GitHub Pages
on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup a v3.x Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install MkDocs and PlugIns
        run: |
          pwd
          pip install mkdocs-material
          pip install mkdocs-callouts
          pip install mkdocs-awesome-pages-plugin
      - name: Run MkDocs to deploy content
        run: |
          pwd
          cp -rp Shaders docs
          mkdocs gh-deploy --force
